In [ ]:
import os

print(os.getcwd())
print(os.listdir())

/workspaces/LLM-zoomcamp-homework/02/llm-zoomcamp-hw5
['.venv', 'main.py', 'starter.py', '.env', '__pycache__', 'README.md', 'homework05.ipynb', 'rag_helper.py', 'pyproject.toml']

/workspaces/LLM-zoomcamp-homework/02/llm-zoomcamp-hw5
['.venv', 'main.py', 'starter.py', 'traces.db', '.env', '__pycache__', 'README.md', 'homework05.ipynb', 'rag_helper.py', 'pyproject.toml']

In [14]:
from dotenv import load_dotenv
import os

load_dotenv("/workspaces/LLM-zoomcamp-homework/02/llm-zoomcamp-hw5/.env")

print(os.getenv("OPENAI_API_KEY"))

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

In [10]:
import os

print(os.getenv("OPENAI_API_KEY"))

None

In [3]:
import sys
print(sys.executable)

/workspaces/LLM-zoomcamp-homework/02/llm-zoomcamp-hw5/.venv/bin/python

In [15]:
from starter import rag

query = "How does the agentic loop keep calling the model until it stops?"
answer = rag.rag(query)
print(answer)

It keeps calling the model in a `while True` loop, and after each response it checks whether the model returned any `function_call` items.

- If there are function calls, the code runs the tools, appends the tool outputs to `messages`, and loops again.
- If there are no function calls, it `break`s out of the loop.

So the stop condition is: **no function calls in the model’s response**.

In [16]:
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import ConsoleSpanExporter, SimpleSpanProcessor

provider = TracerProvider()
provider.add_span_processor(
    SimpleSpanProcessor(ConsoleSpanExporter())
)
trace.set_tracer_provider(provider)

tracer = trace.get_tracer("llm-zoomcamp")

In [17]:
with tracer.start_as_current_span("my_operation") as span:
    # your code here
    span.set_attribute("my_key", "my_value")

{
    "name": "my_operation",
    "context": {
        "trace_id": "0x59de3949ace220d358a8dd79be85a4f5",
        "span_id": "0x05c960595b798e63",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-20T17:23:08.291872Z",
    "end_time": "2026-07-20T17:23:08.291904Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "my_key": "my_value"
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}

In [31]:

from rag_helper import RAGBase
class RAGTraced(RAGBase):

    def rag(self, query):
        with tracer.start_as_current_span("rag"):
            return super().rag(query)

    def search(self, query, num_results=5):
        with tracer.start_as_current_span("search"):
            return super().search(query, num_results=num_results)

    def llm(self, prompt):
        with tracer.start_as_current_span("llm") as span:
            response = super().llm(prompt)

            usage = response.usage

            span.set_attribute("input_tokens", usage.input_tokens)
            span.set_attribute("output_tokens", usage.output_tokens)

            return response

In [24]:
from openai import OpenAI
from dotenv import load_dotenv
from starter import index, client

load_dotenv("/workspaces/LLM-zoomcamp-homework/02/llm-zoomcamp-hw5/.env")

client = OpenAI()

rag = RAGTraced(
    index=index,
    llm_client=client
)

In [25]:
query = "How does the agentic loop keep calling the model until it stops?"

answer = rag.rag(query)

print(answer)

{
    "name": "search",
    "context": {
        "trace_id": "0xc1eb88343df6d6fc1658f93b8d00b605",
        "span_id": "0x7f67ae0d4a4450b6",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x735c40ceb7cb957d",
    "start_time": "2026-07-20T17:38:35.875548Z",
    "end_time": "2026-07-20T17:38:35.878737Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0xc1eb88343df6d6fc1658f93b8d00b605",
        "span_id": "0x6b638b21c43b506b",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x735c40ceb7cb957d",
    "start_time": "2026-07-20T17:38:35.882943Z",
    "end_time": "2026-07-20T17:38:37.826501Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0xc1eb88343df6d6fc1658f93b8d00b605",
        "span_id": "0x735c40ceb7cb957d",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-20T17:38:35.875495Z",
    "end_time": "2026-07-20T17:38:37.827189Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
It keeps calling the model in a `while True` loop and checks whether the model returned any `function_call` items.

- If there **are** function calls, the code runs the tool, appends the tool output to `messages`, and loops again.
- If there are **no** function calls, it means the model has given its final answer, so the loop `break`s.

So the stop condition is simply: **no function calls in the latest response**.

In [27]:
from opentelemetry.sdk.trace.export import SpanExporter, SpanExportResult, SimpleSpanProcessor
from opentelemetry import trace


class ListSpanExporter(SpanExporter):
    def __init__(self):
        self.spans = []

    def export(self, spans):
        self.spans.extend(spans)
        return SpanExportResult.SUCCESS

    def shutdown(self):
        pass


list_exporter = ListSpanExporter()

trace.get_tracer_provider().add_span_processor(
    SimpleSpanProcessor(list_exporter)
)

In [28]:
list_exporter.spans.clear()

query = "How does the agentic loop keep calling the model until it stops?"

answer = rag.rag(query)

span_names = [span.name for span in list_exporter.spans]

print(span_names)
print("Broj spanova:", len(span_names))

{
    "name": "search",
    "context": {
        "trace_id": "0x148286b4b8bb1b0959c50a13c45d44a7",
        "span_id": "0x0785b799458d3c15",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x6abb87af200592fa",
    "start_time": "2026-07-20T17:43:02.355231Z",
    "end_time": "2026-07-20T17:43:02.358648Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0x148286b4b8bb1b0959c50a13c45d44a7",
        "span_id": "0x268e783028b0b246",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x6abb87af200592fa",
    "start_time": "2026-07-20T17:43:02.361007Z",
    "end_time": "2026-07-20T17:43:04.988998Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0x148286b4b8bb1b0959c50a13c45d44a7",
        "span_id": "0x6abb87af200592fa",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-20T17:43:02.355184Z",
    "end_time": "2026-07-20T17:43:04.989798Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
['search', 'llm', 'rag']
Broj spanova: 3

In [32]:
rag = RAGTraced(
    index=index,
    llm_client=client
)

In [33]:
list_exporter.spans.clear()

query = "How does the agentic loop keep calling the model until it stops?"

answer = rag.rag(query)

llm_spans = [span for span in list_exporter.spans if span.name == "llm"]

for span in llm_spans:
    print("Span name:", span.name)
    print("Input tokens:", span.attributes.get("input_tokens"))
    print("Output tokens:", span.attributes.get("output_tokens"))

{
    "name": "search",
    "context": {
        "trace_id": "0xc32f4994aed72fa6ce107678ca5784c6",
        "span_id": "0x03b83cc749c1f857",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x1bf51945bb7faa08",
    "start_time": "2026-07-20T17:47:12.536230Z",
    "end_time": "2026-07-20T17:47:12.539452Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0xc32f4994aed72fa6ce107678ca5784c6",
        "span_id": "0x3ccba25a946e351a",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x1bf51945bb7faa08",
    "start_time": "2026-07-20T17:47:12.540465Z",
    "end_time": "2026-07-20T17:47:14.247866Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "input_tokens": 7111,
        "output_tokens": 123
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0xc32f4994aed72fa6ce107678ca5784c6",
        "span_id": "0x1bf51945bb7faa08",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-20T17:47:12.536192Z",
    "end_time": "2026-07-20T17:47:14.251371Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
Span name: llm
Input tokens: 7111
Output tokens: 123

In [38]:
list_exporter.spans.clear()

query = "How does the agentic loop keep calling the model until it stops?"

answer = rag.rag(query)

for span in list_exporter.spans:
    duration_ms = (span.end_time - span.start_time) / 1_000_000
    print(span.name, round(duration_ms, 2), "ms")

{
    "name": "search",
    "context": {
        "trace_id": "0x306eeb3c6c6dc71d4b73b56341036106",
        "span_id": "0xeb3e4612f67da107",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x63b951d871f0ca6e",
    "start_time": "2026-07-20T17:50:24.181038Z",
    "end_time": "2026-07-20T17:50:24.185188Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0x306eeb3c6c6dc71d4b73b56341036106",
        "span_id": "0xc44b2b16bd9f65f0",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x63b951d871f0ca6e",
    "start_time": "2026-07-20T17:50:24.186230Z",
    "end_time": "2026-07-20T17:50:25.966344Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "input_tokens": 7111,
        "output_tokens": 91
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0x306eeb3c6c6dc71d4b73b56341036106",
        "span_id": "0x63b951d871f0ca6e",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-20T17:50:24.181002Z",
    "end_time": "2026-07-20T17:50:25.967035Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
search 4.15 ms
llm 1780.11 ms
rag 1786.03 ms

In [39]:
import sqlite3
from opentelemetry.sdk.trace.export import SpanExporter, SpanExportResult


class SQLiteSpanExporter(SpanExporter):

    def __init__(self, db_path="traces.db"):
        self.conn = sqlite3.connect(db_path)
        self.conn.execute("""
            CREATE TABLE IF NOT EXISTS spans (
                name TEXT,
                start_time INTEGER,
                end_time INTEGER,
                input_tokens INTEGER,
                output_tokens INTEGER,
                cost REAL
            )
        """)
        self.conn.commit()

    def export(self, spans):
        for span in spans:
            attrs = dict(span.attributes or {})
            self.conn.execute(
                "INSERT INTO spans VALUES (?, ?, ?, ?, ?, ?)",
                (
                    span.name,
                    span.start_time,
                    span.end_time,
                    attrs.get("input_tokens"),
                    attrs.get("output_tokens"),
                    attrs.get("cost"),
                ),
            )
        self.conn.commit()
        return SpanExportResult.SUCCESS

    def shutdown(self):
        self.conn.close()

    def force_flush(self):
        return True

In [45]:
provider = trace.get_tracer_provider()

provider.add_span_processor(
    SimpleSpanProcessor(SQLiteSpanExporter("traces.db"))
)

In [46]:
answer = rag.rag(query)

{
    "name": "search",
    "context": {
        "trace_id": "0xe2637d111c9a7f74b9416582259eaa30",
        "span_id": "0x038978bd12414c42",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x4e3ccb1c7525406e",
    "start_time": "2026-07-20T17:58:27.379428Z",
    "end_time": "2026-07-20T17:58:27.384789Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0xe2637d111c9a7f74b9416582259eaa30",
        "span_id": "0x5f12cdf283379933",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x4e3ccb1c7525406e",
    "start_time": "2026-07-20T17:58:27.395939Z",
    "end_time": "2026-07-20T17:58:28.618017Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "input_tokens": 7111,
        "output_tokens": 91
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0xe2637d111c9a7f74b9416582259eaa30",
        "span_id": "0x4e3ccb1c7525406e",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-20T17:58:27.379356Z",
    "end_time": "2026-07-20T17:58:28.631056Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}

In [47]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("traces.db")

pd.read_sql_query(
    "select distinct name from spans",
    conn,
)

     name
0  search
1     llm
2     rag

In [48]:
list_exporter.spans.clear()
query = "How does the agentic loop keep calling the model until it stops?"

answer = rag.rag(query)

for span in list_exporter.spans:
    duration_ms = (span.end_time - span.start_time) / 1_000_000
    print(span.name, round(duration_ms, 2), "ms")

{
    "name": "search",
    "context": {
        "trace_id": "0xcb3f7f113a044eee4f2b417be5147039",
        "span_id": "0xc908296ab765343c",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xce243e6996df4de9",
    "start_time": "2026-07-20T18:03:36.767983Z",
    "end_time": "2026-07-20T18:03:36.771878Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0xcb3f7f113a044eee4f2b417be5147039",
        "span_id": "0xc87000c327786a64",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xce243e6996df4de9",
    "start_time": "2026-07-20T18:03:36.805022Z",
    "end_time": "2026-07-20T18:03:38.322602Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "input_tokens": 7111,
        "output_tokens": 121
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0xcb3f7f113a044eee4f2b417be5147039",
        "span_id": "0xce243e6996df4de9",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-20T18:03:36.767929Z",
    "end_time": "2026-07-20T18:03:38.330590Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
search 3.9 ms
llm 1517.58 ms
rag 1562.66 ms

In [50]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("traces.db")

pd.read_sql_query("""
SELECT
    name,
    SUM(end_time_unix_nano - start_time_unix_nano)/1000000.0 as total_ms
FROM spans
WHERE name != 'rag'
GROUP BY name
ORDER BY total_ms DESC
""", conn)

DatabaseError: Execution failed on sql '
SELECT
    name,
    SUM(end_time_unix_nano - start_time_unix_nano)/1000000.0 as total_ms
FROM spans
WHERE name != 'rag'
GROUP BY name
ORDER BY total_ms DESC
': no such column: end_time_unix_nano

In [55]:
pd.read_sql_query("""
SELECT
    name,
    SUM(end_time - start_time) / 1000000.0 AS total_ms
FROM spans

GROUP BY name
ORDER BY total_ms DESC
""", conn)

     name     total_ms
0     rag  5628.720350
1     llm  5479.316352
2  search    18.512918

In [56]:
for _ in range(3):
    rag.rag(query)

{
    "name": "search",
    "context": {
        "trace_id": "0x0d6372343afd9a54175f68b4df9b955c",
        "span_id": "0x9b39bd325bd8d999",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xc1ff67c2252c9478",
    "start_time": "2026-07-20T18:09:36.445858Z",
    "end_time": "2026-07-20T18:09:36.452914Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0x0d6372343afd9a54175f68b4df9b955c",
        "span_id": "0x431980e7aab2c3bd",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xc1ff67c2252c9478",
    "start_time": "2026-07-20T18:09:36.466504Z",
    "end_time": "2026-07-20T18:09:38.793792Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "input_tokens": 7111,
        "output_tokens": 103
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0x0d6372343afd9a54175f68b4df9b955c",
        "span_id": "0xc1ff67c2252c9478",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-20T18:09:36.445807Z",
    "end_time": "2026-07-20T18:09:38.800194Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "search",
    "context": {
        "trace_id": "0x46ad4eb28c1a6a59379392f95ab5e634",
        "span_id": "0x6f6228caff660f60",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xc6ead33c25c13993",
    "start_time": "2026-07-20T18:09:38.811555Z",
    "end_time": "2026-07-20T18:09:38.813044Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0x46ad4eb28c1a6a59379392f95ab5e634",
        "span_id": "0xf7dbf5d0dda9fa50",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xc6ead33c25c13993",
    "start_time": "2026-07-20T18:09:38.822361Z",
    "end_time": "2026-07-20T18:09:40.550265Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "input_tokens": 7111,
        "output_tokens": 96
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0x46ad4eb28c1a6a59379392f95ab5e634",
        "span_id": "0xc6ead33c25c13993",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-20T18:09:38.811518Z",
    "end_time": "2026-07-20T18:09:40.560042Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "search",
    "context": {
        "trace_id": "0x638a6c24994acc05130789e172c6b6f7",
        "span_id": "0x847b0291c23436fb",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xfe11194c145752ca",
    "start_time": "2026-07-20T18:09:40.567816Z",
    "end_time": "2026-07-20T18:09:40.569852Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0x638a6c24994acc05130789e172c6b6f7",
        "span_id": "0xd9f89a5c696b0216",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xfe11194c145752ca",
    "start_time": "2026-07-20T18:09:40.577620Z",
    "end_time": "2026-07-20T18:09:43.003853Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "input_tokens": 7111,
        "output_tokens": 84
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0x638a6c24994acc05130789e172c6b6f7",
        "span_id": "0xfe11194c145752ca",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-20T18:09:40.567767Z",
    "end_time": "2026-07-20T18:09:43.013359Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "c05053c8-6e3f-4280-96f4-5272df5f47a5",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}

In [57]:
pd.read_sql_query("""
SELECT input_tokens
FROM spans
WHERE name = 'llm'
""", conn)

   input_tokens
0          7111
1          7111
2          7111
3          7111
4          7111
5          7111
6          7111
7          7111
8          7111
9          7111

In [2]:
import logfire

logfire.configure()
logfire.instrument_pydantic_ai()

No Logfire project credentials found.
All data sent to Logfire must be associated with a project.

Do you want to use one of your existing projects?  [y/n] (y):

KeyboardInterrupt: Interrupted by user

In [1]:
from agent import agent

result = agent.run_sync("How do I run Ollama locally?")

print(result.output)

ModuleNotFoundError: No module named 'agent'